[build]
  functions = "functions"
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[headers]]
  for = "/api/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*"
    content-type = "application/x-www-form-urlencoded"